name: Factory Developers
favicon: null
layout_spectrum: 0.93148
typography_spectrum: 0.24447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#34363d'
    - '#a2a4ac'
    - '#16c5da'
    - '#b3e80e'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
