name: Factory Developers
favicon: null
layout_spectrum: 0.93148
typography_spectrum: 0.24447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff00ff'
    - '#0099ff'
    - '#000000'
    - '#5a5a5a'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.8553460971452296
purpose: []
