name: Factory Developers
favicon: null
layout_spectrum: 0.93148
typography_spectrum: 0.60332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f5e20a'
    - '#3b8674'
    - '#30347d'
    - '#e6522e'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.8553460971452296
purpose: []
