name: Factory Developers
favicon: null
layout_spectrum: 0.18961181957274675
typography_spectrum: 0.7798258666880429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.624671793775633
  lightness: 0.7083009397611022
  saturation: 0.8985766228288412
  rhythmicContrast: 0.8553460971452296
purpose: []
